def procedure(me, refs)
    d = me.createExecutableRun("distributor", "LOCAL")
    m = me.createExecutableRun("manufacturer", "MacOS")
    c = me.createExecutableRun("customer", "FreeBSD")
    d.p[:manu_step_key] = m.getResultKey("step") 
    d.p[:manu_produced_key] = m.getResultKey("produced") 
    d.p[:cust_step_key] = c.getResultKey("step") 
    d.p[:cust_taken_key] = c.getResultKey("taken")
    m.p[:master_step_key] = d.getResultKey("step") 
    c.p[:master_step_key] = d.getResultKey("step") 
    c.p[:dist_holding_key] = d.getResultKey("holding") 
end
